"""Creando is_active en UseCrendetials

Revision ID: 140170cc0973
Revises: ef1d8565ab15
Create Date: 2025-10-16 10:35:41.601023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140170cc0973'
down_revision: Union[str, Sequence[str], None] = 'ef1d8565ab15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
