"""Actualizando model userCrendential

Revision ID: 790d290a5b3d
Revises: bc8808eb0692
Create Date: 2025-10-16 00:51:10.660324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790d290a5b3d'
down_revision: Union[str, Sequence[str], None] = 'bc8808eb0692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
