"""Mover rol a UserCredentials

Revision ID: b3b177ed7e03
Revises: 4d2f56a2361e
Create Date: 2025-10-15 10:31:16.513824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b3b177ed7e03'
down_revision: Union[str, Sequence[str], None] = '4d2f56a2361e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.add_column('user_credentials', sa.Column('role', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_credentials', 'role')
    op.add_column('user', sa.Column('role', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
