"""Creando is_active en UseCrendetials

Revision ID: bc8808eb0692
Revises: b3b177ed7e03
Create Date: 2025-10-15 11:02:52.536305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8808eb0692'
down_revision: Union[str, Sequence[str], None] = 'b3b177ed7e03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_credentials', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_credentials', 'is_active')
    # ### end Alembic commands ###
